apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: demojob
  namespace: tesflask-cicd
  labels:
    app.kubernetes.io/name: testflask-build
spec:
  tower_auth_secret: ansible
  job_template_name: Demo Job Template
  extra_vars:
    app_name: testflask